Repository programnoir/GDTemplate, pull requests merged in 2023-07, with the labels that each got.

#10 Fixes crashes after clicking new game and settings
  rooms/room_main/signals/signals-main.gd
  ui/ui_settings/ui_button_tab/ui-button-tab.gd
Labels: abrupt crash (high priority)

#16 Corrects value passed to nLabelWindowScale
  ui/ui_settings/ui_tab_video/ui-tab-video.gd
Labels: bug

#17 Corrects tween error and fade states
  addons/gdtemplate/ui/global-ui-screenfade.gd
  rooms/room_main/signals/signals-main.gd
Labels: bug

#19 Font selection per language
  addons/gdtemplate/autoload/global-theme.gd
  addons/gdtemplate/autoload/global-user-settings.gd
  addons/gdtemplate/plugin.gd
  addons/gdtemplate/ui/ui_button_cycle/ui-button-cycle.gd
  addons/gdtemplate/ui/ui_button_cycle/ui-button-cycle.tscn
  addons/gdtemplate/ui/ui_button_tab/ui-button-tab.gd
  addons/gdtemplate/ui/ui_button_tab/ui-button-tab.tscn
  assets/fonts/Atkinson-Hyperlegible-Regular-102.ttf
  assets/fonts/Atkinson-Hyperlegible-Regular-102.ttf.import
  assets/fonts/BIZUDGothic-Regular.ttf.import
  assets/fonts/NotoSansJP-Regular.ttf.import
  assets/fonts/OpenDyslexic-Regular.otf
  assets/fonts/OpenDyslexic-Regular.otf.import
  assets/fonts/license-atkinson-hyperlegible-regular-102.txt
  assets/fonts/license-bizudgothic.txt
  assets/fonts/license-notosansjp-regular.txt
  assets/fonts/license-opendyslexic3-regular.txt
  data/resources/res-default-bus-layout.tres
  data/resources/res-theme-default.tres
  data/translations/translations.csv
  default_bus_layout.tres
  project.godot
  rooms/room_main/room-main.gd
  rooms/room_main/room-main.tscn
  rooms/room_main/signals/signals-main.gd
  ui/ui_first_setup/signals-ui-first-setup.gd
  ui/ui_first_setup/ui-first-setup.gd
  ui/ui_first_setup/ui-first-setup.tscn
  ui/ui_main_menu/ui-main-menu.gd
  ui/ui_main_menu/ui-main-menu.tscn
  ui/ui_settings/signals/signals-ui-settings.gd
  ui/ui_settings/ui-settings.gd
  ui/ui_settings/ui-settings.tscn
  ui/ui_settings/ui_button_tab/ui-button-tab.gd
  ui/ui_settings/ui_button_tab/ui-button-tab.tscn
  ui/ui_settings/ui_tab_accessibility/signals/signals-ui-tab-accessibility.gd
  ui/ui_settings/ui_tab_accessibility/ui-tab-accessibility.gd
  ui/ui_settings/ui_tab_controls/ui-tab-controls.gd
  ui/ui_settings/ui_tab_controls/ui_action/ui-action.gd
  ui/ui_settings/ui_tab_controls/ui_action/ui-action.tscn
  ui/ui_settings/ui_tab_video/ui-tab-video.gd
Labels: game ui/ux, user accessibility/languages

#20 Adds borderless mode option
  addons/gdtemplate/autoload/global-user-settings.gd
  data/translations/translations.csv
  ui/ui_settings/ui-settings.tscn
  ui/ui_settings/ui_tab_video/signals/signals-ui-tab-video.gd
  ui/ui_settings/ui_tab_video/ui-tab-video.gd
Labels: game ui/ux

#21 Translates default actions and inputevents in Controls tab.
  addons/gdtemplate/autoload/global-action-config.gd
  addons/gdtemplate/autoload/global-theme.gd
  addons/gdtemplate/autoload/global-user-settings.gd
  addons/gdtemplate/plugin.gd
  data/translations/binds.csv
  data/translations/translations.csv
  project.godot
  ui/ui_first_setup/signals/signals-ui-first-setup.gd
  ui/ui_first_setup/ui-first-setup.gd
  ui/ui_first_setup/ui-first-setup.tscn
  ui/ui_main_menu/ui-main-menu.tscn
  ui/ui_settings/ui-settings.tscn
  ui/ui_settings/ui_tab_accessibility/ui-tab-accessibility.gd
  ui/ui_settings/ui_tab_controls/ui-tab-controls.gd
  ui/ui_settings/ui_tab_controls/ui_action/ui-action.gd
  ui/ui_settings/ui_tab_controls/ui_popup_set_bind/ui-popup-set-bind.gd
Labels: user accessibility/languages
